name: ml
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.8.0
  - notebook=7.0.6
  - numpy=1.26.0
  - pandas=2.1.1
  - pip=23.3
  - python=3.11.5
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - seaborn=0.12.2
  - statsmodels=0.14.0
prefix: /Users/zanelim/miniconda3/envs/ml
